{
 "title": "Logging Dashboard via Loki v3",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "container_name",
    "label": "Container",
    "query": "label_values({container_name=~\".+\"}, container_name)"
   },
   {
    "name": "service_name",
    "label": "Service",
    "query": "label_values({container_name=~\"$container_name\"}, service_name)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({container_name=~\"$container_name\"}, instance)"
   },
   {
    "name": "searchable_pattern",
    "label": "Search regex (case insensitive)"
   },
   { "name": "DS_LOKI", "label": "Data Source", "query": "loki" },
   { "name": "alloy_exclude", "query": "${VAR_ALLOY_EXCLUDE}" }
  ]
 },
 "panels": [
  { "title": "All services statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "\"$searchable_pattern\" pattern matches distribution per service",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(({container_name=~\"$container_name\", service_name=~\"$service_name\", instance=~\"$instance\"} |~ \"(?i)$searchable_pattern\" !~ \"(?i)$[[service_name]]_exclude\")[$__interval])) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Historical \"$searchable_pattern\" pattern matches distribution per service",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate(({container_name=~\"$container_name\", instance=~\"$instance\", service_name=~\"$service_name\"} |~ \"(?i)$searchable_pattern\" !~ \"(?i)$[[service_name]]_exclude\")[30s])) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "$service_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "service_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Live logs",
     "type": "logs",
     "description": "Live logs is a like 'tail -f' in a real time",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "direction": "forward",
       "expr": "{container_name=~\"$container_name\", service_name=~\"$service_name\", instance=~\"$instance\"} |~ \"(?i)$searchable_pattern\" !~ \"(?i)$[[service_name]]_exclude\""
      }
     ]
    }
   ]
  }
 ]
}