{
 "title": "Kea DHCP",
 "description": "Kea exporter - https://github.com/mweinelt/kea-exporter",
 "tags": [
  "kea",
  "dhcp",
  "router"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(kea_dhcp4_addresses_total,instance)"
    }
   },
   {
    "name": "ipv4_pool",
    "query": {
     "query": "label_values(kea_dhcp4_addresses_assigned_total,pool)"
    }
   },
   {
    "name": "ipv4_subnet",
    "query": {
     "query": "label_values(kea_dhcp4_addresses_assigned_total,subnet)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "IPv4", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "$ipv4_pool",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "repeat": "ipv4_pool",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kea_dhcp4_addresses_assigned_total{instance=\"$host\", pool=~\"$ipv4_pool\"}/kea_dhcp4_addresses_total{instance=\"$host\", pool=~\"$ipv4_pool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Conflicts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "$ipv4_subnet",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "repeat": "ipv4_subnet",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kea_dhcp4_reservation_conflicts_total{instance=\"$host\", subnet=~\"$ipv4_subnet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Addresses statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "$ipv4_pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "repeat": "ipv4_pool",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kea_dhcp4_addresses_assigned_total{instance=\"$host\", pool=~\"$ipv4_pool\"}",
     "legendFormat": "assigned"
    },
    {
     "expr": "kea_dhcp4_addresses_declined_total{instance=\"$host\", pool=~\"$ipv4_pool\"}",
     "legendFormat": "declined"
    },
    {
     "expr": "kea_dhcp4_addresses_declined_reclaimed_total{instance=\"$host\", pool=~\"$ipv4_pool\"}",
     "legendFormat": "declined reclaimed"
    }
   ]
  },
  { "title": "Packets statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Packet received - IPv4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "rate(kea_dhcp4_packets_received_total{instance=\"$host\", operation=\"ack\"}[$__rate_interval])",
     "legendFormat": "ack"
    },
    {
     "expr": "rate(kea_dhcp4_packets_received_total{instance=\"$host\", operation=\"discover\"}[$__rate_interval])",
     "legendFormat": "discover"
    },
    {
     "expr": "rate(kea_dhcp4_packets_received_total{instance=\"$host\", operation=\"request\"}[$__rate_interval])",
     "legendFormat": "request"
    },
    {
     "expr": "rate(kea_dhcp4_packets_received_total{instance=\"$host\", operation=\"drop\"}[$__rate_interval])",
     "legendFormat": "drop"
    }
   ]
  },
  {
   "title": "Packet sent - IPv4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "rate(kea_dhcp4_packets_sent_total{instance=\"$host\", operation=\"ack\"}[$__rate_interval])",
     "legendFormat": "ack"
    },
    {
     "expr": "rate(kea_dhcp4_packets_sent_total{instance=\"$host\", operation=\"nak\"}[$__rate_interval])",
     "legendFormat": "nak"
    },
    {
     "expr": "rate(kea_dhcp4_packets_sent_total{instance=\"$host\", operation=\"offer\"}[$__rate_interval])",
     "legendFormat": "offer"
    }
   ]
  }
 ]
}