[secrets]
ssh-rsa = { regex = false }
ssh-ed25519 = { regex = false }
AAAAB3NzaC1 = { regex = false }
AAAAE2VjZHNh = { regex = false }
AAAAC3NzaC1 = { regex = false }

# GPG key ID
"D85B52C9288A138E" = { regex = false }

# GitHub tokens
"***REDACTED-GITHUB-PAT***" = { regex = false }

# Google API credentials
"***REDACTED-GOOGLE-API-KEY***" = { regex = false }
"***REDACTED-GOOGLE-OAUTH-SECRET***" = { regex = false }
"***REDACTED-GOOGLE-SECRET***" = { regex = false }

# Keycloak
"***REDACTED-KEYCLOAK-SECRET-1***" = { regex = false }
"***REDACTED-KEYCLOAK-SECRET-2***" = { regex = false }
"***REDACTED-KEYCLOAK-SECRET-3***" = { regex = false }

# Recyclarr API keys
"***REDACTED-RECYCLARR-KEY-1***" = { regex = false }
"***REDACTED-RECYCLARR-KEY-2***" = { regex = false }

[allowlist]
paths = [
  "modules/users/zeev/default.nix",
  "modules/networking/ssh-hosts.nix",
  "modules/TUI/common/default.nix",
  "modules/GUI/thunderbird/default.nix",
  "modules/options/defaults.nix",
  "modules/GUI/chromium/default.nix",
  "home/matebook/default.nix",
  "modules/services/nixarr/recyclarr.yaml",
  "modules/security/keycloak/homelab-realm.json",
  "modules/security/keycloak/default.nix",
  "modules/services/nixarr/wg.conf",
  "hosts/nixos/wsl/default.nix",
  "hosts/nixos/homeserver/default.nix",
  "hosts/nixos/matebook/default.nix",
  "modules/users/zeev/default.nix",
]
