keys:
    - &zeev age18pkk5washz5p8vl4tkemulvv8x23deaqwqqvfmwu7r7vwvjfwdqsg657vd
    - &pgp REDACTED
creation_rules:
  - path_regex: 'secrets/.*\.yaml$'
    key_groups:
      - age:
          - *zeev
      - pgp:
          - *pgp    

    