disabled = [
    'empty_pattern',
    'manual_inherit',
    'manual_inherit_from'
]
nix_version = '2.31.2'
ignore = [
    '.direnv/**',
    'result*/**',
    'secrets/**',
    '**/*.age',
    '**/*.gpg',
    '.git/**',
    '.github/**'
]
