[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]

[formatter.deadnix]
command = "deadnix"
includes = ["*.nix"]

[formatter.shfmt]
command = "shfmt"
includes = ["*.sh", "*.bash", "*.envrc", "*.envrc.*"]

[formatter.just]
command = "just"
includes = [".justfile"]

[formatter.rustfmt]
command = "rustfmt"
includes = ["*.rs"]

[formatter.yamlfmt]
command = "yamlfmt"
includes = ["*.yaml", "*.yml"]

[formatter.toml-sort]
command = "toml-sort"
includes = ["*.toml"]

[formatter.dockfmt]
command = "dockfmt"
includes = ["*.Dockerfile", "docker-compose.yml"]

[formatter.prettier]
command = "prettier"
includes = [
    "*.cjs",
    "*.css",
    "*.html",
    "*.js",
    "*.json5",
    "*.jsx",
    "*.mdx",
    "*.mjs",
    "*.scss",
    "*.ts",
    "*.tsx",
    "*.vue",
    "*.json"
]

[global]
excludes = [
    "secrets/*",
    "*.png",
    "*.jpeg",
    "*.toml",
    "*.clan-flake",
    "*.code-workspace",
    "*.pub",
    "*.typed",
    "*.age",
    "*.list",
    "*.desktop",
    "modules/services/homepage/default.nix"
]
