# Oracle Cloud Free Tier ARM VM — aarch64, 2 OCPU, 12GB RAM, 100GB disk.
# Boot device: /dev/sda (paravirtualized virtio block).
# Generated by nixos-anywhere; regenerated automatically by nixos-facter if
# facter.json is present. Keep this file minimal — facter handles the rest.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot = {
    initrd.availableKernelModules = ["xhci_pci" "virtio_pci" "usbhid"];
    initrd.kernelModules = [];
    kernelModules = [];
    extraModulePackages = [];
    loader = {
      grub = {
        enable = true;
        device = "/dev/sda";
        efiSupport = false;
      };
      efi.canTouchEfiVariables = lib.mkDefault false;
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "ext4";
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";

  # Facter report — populated after first nixos-anywhere deploy
  # facter.reportPath = ./facter.json;

  hardware.enableRedistributableFirmware = lib.mkDefault true;
  services.qemuGuest.enable = true;

  # Oracle Cloud uses virtio; no special network device renaming needed
  networking.useDHCP = lib.mkDefault true;
}
