{
 "title": "Caddy",
 "tags": [ "caddy" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,10m,30m,1h,2h,4h,8h" },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(caddy_http_request_duration_seconds_count{handler=\"reverse_proxy\"}, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Caddy Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"caddy\"} == 1)"
    }
   ]
  },
  {
   "title": "Requests per Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{handler=\"reverse_proxy\",host=~\"$host\"}[$interval])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Apdex score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(caddy_http_request_duration_seconds_bucket{le=\"0.25\",code=\"200\",handler=\"reverse_proxy\",host=~\"$host\"}[$interval])) by (method) + sum(rate(caddy_http_request_duration_seconds_bucket{le=\"1\",code=\"200\",handler=\"reverse_proxy\",host=~\"$host\"}[$interval])) by (method)) / 2 / sum(rate(caddy_http_request_duration_seconds_count{code=\"200\",handler=\"reverse_proxy\",host=~\"$host\"}[$interval])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Http Code",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{handler=\"reverse_proxy\",host=~\"$host\"}[$interval])) by (method, code)",
     "legendFormat": "{{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Top slow hosts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(15, sum by (host) (rate(caddy_http_request_duration_seconds_sum{handler=\"reverse_proxy\",host=~\"$host\"}[$interval])) / sum by (host) (rate(caddy_http_request_duration_seconds_count{handler=\"reverse_proxy\",host=~\"$host\"}[$interval])))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Most requested hosts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15, sum by (host, code) (rate(caddy_http_request_duration_seconds_count{handler=\"reverse_proxy\",host=~\"$host\"}[$interval])) > 0)",
     "legendFormat": "{{host}} {{code}}"
    }
   ]
  },
  { "title": "SLO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Hosts failing SLO of 1s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (sum by (host) (rate(caddy_http_request_duration_seconds_bucket{le=\"1\",handler=\"reverse_proxy\",host=~\"$host\"}[$interval])) / sum by (host) (rate(caddy_http_request_duration_seconds_count{handler=\"reverse_proxy\",host=~\"$host\"}[$interval]))) > 0",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Hosts failing SLO of 250ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (sum by (host) (rate(caddy_http_request_duration_seconds_bucket{le=\"0.25\",handler=\"reverse_proxy\",host=~\"$host\"}[$interval])) / sum by (host) (rate(caddy_http_request_duration_seconds_count{handler=\"reverse_proxy\",host=~\"$host\"}[$interval]))) > 0",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "HTTP Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "2xx over $interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15, sum by (host, method, code) (rate(caddy_http_request_duration_seconds_count{code=~\"2..\",handler=\"reverse_proxy\",host=~\"$host\"}[$interval])) > 0)",
     "legendFormat": "{{host}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "5xx over $interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15, sum by (host, method, code) (rate(caddy_http_request_duration_seconds_count{code=~\"5..\",handler=\"reverse_proxy\",host=~\"$host\"}[$interval])) > 0)",
     "legendFormat": "{{host}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Other codes over $interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15, sum by (host, method, code) (rate(caddy_http_request_duration_seconds_count{code!~\"2..|5..\",handler=\"reverse_proxy\",host=~\"$host\"}[$interval])) > 0)",
     "legendFormat": "{{host}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Requests Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(15, sum by (host, method) (rate(caddy_http_request_size_bytes_sum{handler=\"reverse_proxy\",host=~\"$host\"}[$interval])) > 0)",
     "legendFormat": "{{host}} {{method}}"
    }
   ]
  },
  {
   "title": "Responses Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(15, sum by (host, method) (rate(caddy_http_response_size_bytes_sum{handler=\"reverse_proxy\",host=~\"$host\"}[$interval])) > 0)",
     "legendFormat": "{{host}} {{method}}"
    }
   ]
  },
  {
   "title": "Requests in flight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(caddy_http_requests_in_flight{handler=\"reverse_proxy\"}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Upstream health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "caddy_reverse_proxy_upstreams_healthy",
     "legendFormat": "{{upstream}}"
    }
   ]
  }
 ]
}