# GCP e2-micro (2 vCPU / 1 GB RAM / 30 GB disk), us-central1.
# Boot device: /dev/vda (virtio-blk, GCP standard).
# Generated by nixos-anywhere; regenerated automatically by nixos-facter if
# facter.json is present. Keep this file minimal — facter handles the rest.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot = {
    initrd.availableKernelModules = [
      "virtio_pci"
      "virtio_scsi"
      "virtio_blk"
      "virtio_net"
      "9p"
      "9pnet_virtio"
      "sd_mod"
      "ata_piix"
    ];
    initrd.kernelModules = [];
    kernelModules = [];
    extraModulePackages = [];
    loader = {
      grub = {
        enable = true;
        device = "/dev/sda";
        efiSupport = false;
      };
      efi.canTouchEfiVariables = lib.mkDefault false;
    };
  };

  fileSystems."/" = {
    device = "/dev/sda1";
    fsType = "ext4";
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Facter report — populated after first nixos-anywhere deploy
  # facter.reportPath = ./facter.json;

  hardware.enableRedistributableFirmware = lib.mkDefault true;
  services.qemuGuest.enable = true;

  networking.useDHCP = lib.mkDefault true;
}
