{config, ...}: {
  networking.firewall.allowedTCPPorts = [
    config.my.network.ports.loki
  ];

  systemd.tmpfiles.rules = [
    "d /var/lib/loki/rules 0755 loki loki -"
    "d /var/lib/loki/rules/fake 0755 loki loki -"
    "d /var/lib/loki/rules-temp 0755 loki loki -"
    "L+ /var/lib/loki/rules/fake/homeserver.yaml - - - - ${./alerts/loki-rules.yaml}"
  ];

  services.loki = {
    enable = true;
    configuration = {
      auth_enabled = false;
      server.http_listen_port = config.my.network.ports.loki;
      ingester = {
        lifecycler = {
          address = "127.0.0.1";
          ring = {
            kvstore.store = "inmemory";
            replication_factor = 1;
          };
        };
        chunk_idle_period = "1h";
        max_chunk_age = "1h";
        chunk_target_size = 1048576;
        chunk_retain_period = "30s";
      };
      schema_config.configs = [
        {
          from = "2025-01-01";
          store = "tsdb";
          object_store = "filesystem";
          schema = "v13";
          index = {
            prefix = "index_";
            period = "24h";
          };
        }
      ];
      storage_config = {
        tsdb_shipper = {
          active_index_directory = "/var/lib/loki/tsdb-index";
          cache_location = "/var/lib/loki/tsdb-cache";
        };
        filesystem.directory = "/var/lib/loki/chunks";
      };
      compactor = {
        working_directory = "/var/lib/loki/compactor";
        compaction_interval = "10m";
        retention_enabled = true;
        retention_delete_delay = "2h";
        retention_delete_worker_count = 150;
        delete_request_store = "filesystem";
        compactor_ring.kvstore.store = "inmemory";
      };
      limits_config = {
        retention_period = "30d";
        reject_old_samples = true;
        reject_old_samples_max_age = "30d";
        ingestion_rate_mb = 16;
        ingestion_burst_size_mb = 32;
        allow_structured_metadata = false;
      };
      query_range.cache_results = true;
      frontend.scheduler_address = "";
      frontend_worker.scheduler_address = "";
      ruler = {
        storage = {
          type = "local";
          local.directory = "/var/lib/loki/rules";
        };
        rule_path = "/var/lib/loki/rules-temp";
        alertmanager_url = "http://127.0.0.1:${toString config.my.network.ports.alertmanager}";
        enable_alertmanager_v2 = true;
        enable_api = true;
        ring.kvstore.store = "inmemory";
      };
    };
  };

  # Generated by `shh service finish-profile loki.service` after a live
  # profiling run (2026-09-14) with kernel.yama.ptrace_scope temporarily
  # relaxed to 0 (see hosts/nixos/homeserver/hardening.nix). PrivateNetwork/
  # IPAddressDeny deliberately not set: Loki has to accept push traffic
  # from Alloy over the LAN. CapabilityBoundingSet was previously fully
  # unset (verified via `systemctl show` before this change) — shh's
  # partial denylist below is strictly an improvement, unlike the *arr
  # services where a stricter fully-empty set was already in place.
  systemd.services.loki.serviceConfig = {
    ProtectSystem = "full";
    ProtectHome = true;
    PrivateTmp = "disconnected";
    PrivateDevices = true;
    PrivateMounts = true;
    ProtectKernelTunables = true;
    ProtectKernelModules = true;
    ProtectKernelLogs = true;
    ProtectControlGroups = true;
    LockPersonality = true;
    RestrictRealtime = true;
    ProtectClock = true;
    MemoryDenyWriteExecute = true;
    RestrictAddressFamilies = ["AF_INET" "AF_INET6" "AF_NETLINK" "AF_UNIX"];
    SocketBindDeny = ["ipv4:udp" "ipv6:udp"];
    CapabilityBoundingSet = "~CAP_BLOCK_SUSPEND CAP_BPF CAP_CHOWN CAP_IPC_LOCK CAP_KILL CAP_MKNOD CAP_NET_RAW CAP_PERFMON CAP_SYS_BOOT CAP_SYS_CHROOT CAP_SYS_MODULE CAP_SYS_NICE CAP_SYS_PACCT CAP_SYS_PTRACE CAP_SYS_TIME CAP_SYS_TTY_CONFIG CAP_SYSLOG CAP_WAKE_ALARM";
    # Each group needs its own "~" as a separate list entry: systemd only
    # applies a leading "~" to the first token of a value, so a single
    # space-joined string here would silently drop the ":EPERM" handling
    # for every group after the first ("Allow-listed system calls cannot
    # take error number, ignoring" — hit this exact bug on the *arr
    # services earlier today, see their git history).
    SystemCallFilter = [
      "~@aio:EPERM"
      "~@chown:EPERM"
      "~@clock:EPERM"
      "~@cpu-emulation:EPERM"
      "~@debug:EPERM"
      "~@ipc:EPERM"
      "~@keyring:EPERM"
      "~@memlock:EPERM"
      "~@module:EPERM"
      "~@mount:EPERM"
      "~@obsolete:EPERM"
      "~@pkey:EPERM"
      "~@privileged:EPERM"
      "~@raw-io:EPERM"
      "~@reboot:EPERM"
      "~@resources:EPERM"
      "~@sandbox:EPERM"
      "~@setuid:EPERM"
      "~@swap:EPERM"
    ];
  };
}
