{ config, pkgs, lib, ... }:

{
  services.miniflux = {
    enable = true;
    # This is the correct, idiomatic way to provide the admin credentials.
    # It points to the file generated by your 'miniflux_secrets' sops group.
    adminCredentialsFile = config.sops.secrets.miniflux_secrets.path;

    config = {
      # The admin user/pass are now handled by the file above.
      # CREATE_ADMIN = 1; is the default and should be kept to ensure
      # the user is created on the first run.
      BASE_URL = "https://rss.labhome.work";
      DATABASE_URL = "postgres://miniflux:${config.sops.secrets.database_passwords.miniflux_db_password}@/miniflux";
      PORT = "8086";
      RUN_AS_USER = "miniflux";
    };
  };
}
