{
  config,
  lib,
  ...
}: {
  imports = [
    ((import ../lib/pg-env.nix {inherit lib;}) {
      name = "radarr";
      envLines = [
        "RADARR__POSTGRES__HOST=127.0.0.1"
        "RADARR__POSTGRES__PORT=5432"
        "RADARR__POSTGRES__USER=radarr"
        "RADARR__POSTGRES__MAINDB=radarr"
        "RADARR__POSTGRES__LOGDB=radarr-log"
        "RADARR__POSTGRES__PASSWORD=%s"
      ];
      passwordSecretPath = config.sops.secrets.radarr_db_password.path;
    })
  ];

  # Radarr reads RADARR__POSTGRES__* env vars natively -- no need to
  # hand-edit config.xml via xmlstarlet.
  services.radarr = {
    enable = true;
    user = "radarr";
    group = "radarr";
    dataDir = "/data/media/.state/nixarr/radarr";
    settings.server.port = config.my.network.ports.radarr;
  };

  systemd.services.radarr = {
    after = ["data.mount" "radarr-pg-env.service"];
    requires = ["data.mount" "radarr-pg-env.service"];
    serviceConfig = {
      EnvironmentFile = "/run/radarr-secrets/pg-env";
      # nixpkgs' module hardcodes 0022; we need group-writable output to
      # match the rest of the media stack's shared "media" group access.
      UMask = lib.mkForce "0002";

      # No AF_INET6 — homeserver-only module, networking.enableIPv6 = false
      # there. nixpkgs hardcodes AF_INET6 here; with it present, `shh`
      # (strace-profiling hardening helper) crashes reading
      # /proc/sys/net/ipv6/bindv6only, which doesn't exist when IPv6 is
      # fully disabled (same crash seen profiling prowlarr.service).
      RestrictAddressFamilies = lib.mkForce ["AF_INET" "AF_UNIX"];

      # Generated by `shh service finish-profile radarr.service` after a
      # live profiling run (2026-09-14) with kernel.yama.ptrace_scope
      # temporarily relaxed to 0 — see hosts/nixos/homeserver/hardening.nix.
      ProtectSystem = "full";
      PrivateMounts = true;
      ProtectKernelModules = true;
      ProtectControlGroups = true;
      LockPersonality = true;
      RestrictRealtime = true;
      ProtectClock = true;
      SocketBindDeny = ["ipv4:udp" "ipv6:tcp" "ipv6:udp"];
      # Single-line value, exactly as shh printed it: the leading "~"
      # inverts the whole list into a denylist — splitting this into
      # separate Nix list entries would emit multiple systemd directive
      # lines and only the first would carry the "~", breaking the semantics.
      # (This concern is specific to CapabilityBoundingSet: unlike
      # SystemCallFilter below, there's no per-item ":ERRNO" suffix here to
      # trip over, so one merged "~"-prefixed line is fine.)
      CapabilityBoundingSet = lib.mkForce "~CAP_BLOCK_SUSPEND CAP_BPF CAP_CHOWN CAP_IPC_LOCK CAP_KILL CAP_MKNOD CAP_NET_RAW CAP_PERFMON CAP_SYS_BOOT CAP_SYS_CHROOT CAP_SYS_MODULE CAP_SYS_PACCT CAP_SYS_PTRACE CAP_SYS_TIME CAP_SYS_TTY_CONFIG CAP_SYSLOG CAP_WAKE_ALARM";
      # CORRECTED 2026-09-14 (second correction): a Nix list of
      # "~@group:EPERM" strings renders as one "SystemCallFilter=" line per
      # element, but NixOS/systemd only keeps the leading "~" on the first
      # line — the rest silently parse as allow-list entries, which can't
      # carry ":EPERM" ("Allow-listed system calls cannot take error
      # number, ignoring"). The documented, unambiguous pattern: set
      # SystemCallErrorNumber= once, and give SystemCallFilter a single
      # "~"-prefixed string with no per-item ":ERRNO" — the leading "~"
      # then applies to the whole list exactly once, no merge ambiguity.
      SystemCallErrorNumber = "EPERM";
      SystemCallFilter = "~@aio @chown @clock @cpu-emulation @debug @keyring @memlock @module @mount @obsolete @pkey @privileged @raw-io @reboot @sandbox @setuid @swap";
    };
  };
}
