{
  config,
  pkgs,
  lib,
  ...
}: {
  users.users.komga = {
    isSystemUser = true;
    group = "komga";
    extraGroups = [
      "users"
      "media"
    ];
  };
  users.groups.komga = {};

  services.komga = {
    enable = true;
    settings = {
      "spring.datasource.url" = "jdbc:h2:file:/var/lib/komga/database;DB_CLOSE_ON_EXIT=FALSE";
      server.port = config.my.network.ports.komga;
    };
  };

  systemd.services.komga.serviceConfig = {
    UMask = "0002";
    BindPaths = [
      "/data/media/comics"
      "/data/media/manga"
      "/data/media/books"
    ];

    # komga is homeserver-only, and /tmp + /var/tmp are noexec there
    # (nix-mineral filesystem hardening default, see
    # hosts/nixos/homeserver/hardening.nix). sqlite-jdbc (bundled inside
    # komga for its search index) extracts its native .so to java.io.tmpdir
    # and mmaps it PROT_EXEC — under noexec that fails, and sqlite-jdbc
    # mis-reports the failure as "NativeLibraryNotFoundException" instead of
    # a permission error. /var/lib is already carved out exec on homeserver
    # (filesystems.normal."/var/lib" in hardening.nix, for the *arr stack's
    # own scripts) — point java.io.tmpdir at /var/lib/komga/tmp instead of
    # PrivateTmp's /tmp.
    # nixpkgs' komga wrapper only puts libwebp on LD_LIBRARY_PATH (verified
    # via `cat` on the wrapper script) — libheif and libjxl are both
    # available in nixpkgs but the package doesn't wire them in, so their
    # image-format plugins log "Could not load libheif"/"Could not load
    # libjxl" and silently disable at startup (confirmed live 2026-09-14).
    # The wrapper prepends its own LD_LIBRARY_PATH entry onto whatever it
    # inherits, so this is additive, not a fight over who wins.
    Environment = [
      "JAVA_TOOL_OPTIONS=-Djava.io.tmpdir=/var/lib/komga/tmp"
      "LD_LIBRARY_PATH=${lib.makeLibraryPath [pkgs.libheif pkgs.libjxl]}"
    ];

    # Generated by `shh service finish-profile komga.service` after a live
    # profiling run (2026-09-14) with kernel.yama.ptrace_scope temporarily
    # relaxed to 0 (see hosts/nixos/homeserver/hardening.nix). Verify after
    # rebuild that komga still serves on its port. shh's suggested
    # SocketBindDeny included "ipv4:tcp" — confirmed live 2026-09-14 this
    # breaks komga outright (Tomcat's own listening bind is a raw AF_INET
    # socket, not dual-stack IPv6 as guessed initially): "Unable to start
    # embedded Tomcat server ... Caused by: java.net.SocketException:
    # Operation not permitted". shh must have derived this from a
    # profiling window that never captured the real bind (e.g. Tomcat was
    # already listening from a prior invocation when the trace started).
    # Left out below — do not re-add "ipv4:tcp".
    ProtectSystem = "full";
    ProtectHome = true;
    PrivateTmp = "disconnected";
    PrivateDevices = true;
    PrivateMounts = true;
    ProtectKernelTunables = true;
    ProtectKernelModules = true;
    ProtectKernelLogs = true;
    ProtectControlGroups = true;
    LockPersonality = true;
    RestrictRealtime = true;
    ProtectClock = true;
    RestrictAddressFamilies = ["AF_INET" "AF_INET6"];
    SocketBindDeny = ["ipv4:udp" "ipv6:tcp" "ipv6:udp"];
    CapabilityBoundingSet = lib.mkForce "~CAP_BLOCK_SUSPEND CAP_BPF CAP_CHOWN CAP_IPC_LOCK CAP_MKNOD CAP_NET_RAW CAP_PERFMON CAP_SYS_BOOT CAP_SYS_CHROOT CAP_SYS_MODULE CAP_SYS_NICE CAP_SYS_PACCT CAP_SYS_PTRACE CAP_SYS_TIME CAP_SYSLOG CAP_WAKE_ALARM";
    # Each group needs its own "~" as a separate list entry: systemd only
    # applies a leading "~" to the first token of a value, so a single
    # space-joined string here would silently drop the ":EPERM" handling
    # for every group after the first ("Allow-listed system calls cannot
    # take error number, ignoring" — hit this exact bug on the other *arr
    # services today, see their git history).
    SystemCallFilter = [
      "~@aio:EPERM"
      "~@chown:EPERM"
      "~@clock:EPERM"
      "~@cpu-emulation:EPERM"
      "~@debug:EPERM"
      "~@keyring:EPERM"
      "~@memlock:EPERM"
      "~@module:EPERM"
      "~@mount:EPERM"
      "~@obsolete:EPERM"
      "~@pkey:EPERM"
      "~@privileged:EPERM"
      "~@raw-io:EPERM"
      "~@reboot:EPERM"
      "~@resources:EPERM"
      "~@sandbox:EPERM"
      "~@setuid:EPERM"
      "~@swap:EPERM"
    ];
  };

  systemd.tmpfiles.rules = [
    "d /var/lib/komga 0750 komga komga -"
    "d /var/lib/komga/tmp 0750 komga komga -"
  ];
}
