{
  config,
  pkgs,
  lib,
  ...
}: {
  users.users.komga = {
    isSystemUser = true;
    group = "komga";
    extraGroups = [
      "users"
      "media"
    ];
  };
  users.groups.komga = {};

  services.komga = {
    enable = true;
    settings = {
      "spring.datasource.url" = "jdbc:h2:file:/var/lib/komga/database;DB_CLOSE_ON_EXIT=FALSE";
      server.port = config.my.network.ports.komga;
    };
  };

  systemd.services.komga.serviceConfig = {
    UMask = "0002";
    BindPaths = [
      "/data/media/comics"
      "/data/media/manga"
      "/data/media/books"
    ];

    # komga is homeserver-only, and /tmp + /var/tmp are noexec there
    # (nix-mineral filesystem hardening default, see
    # hosts/nixos/homeserver/hardening.nix). sqlite-jdbc (bundled inside
    # komga for its search index) extracts its native .so to java.io.tmpdir
    # and mmaps it PROT_EXEC — under noexec that fails, and sqlite-jdbc
    # mis-reports the failure as "NativeLibraryNotFoundException" instead of
    # a permission error. /var/lib is already carved out exec on homeserver
    # (filesystems.normal."/var/lib" in hardening.nix, for the *arr stack's
    # own scripts) — point java.io.tmpdir at /var/lib/komga/tmp instead of
    # PrivateTmp's /tmp.
    # nixpkgs' komga wrapper only puts libwebp on LD_LIBRARY_PATH (verified
    # via `cat` on the wrapper script) — libheif and libjxl are both
    # available in nixpkgs but the package doesn't wire them in, so their
    # image-format plugins log "Could not load libheif"/"Could not load
    # libjxl" and silently disable at startup (confirmed live 2026-09-14).
    # The wrapper prepends its own LD_LIBRARY_PATH entry onto whatever it
    # inherits, so this is additive, not a fight over who wins.
    Environment = [
      "JAVA_TOOL_OPTIONS=-Djava.io.tmpdir=/var/lib/komga/tmp"
      "LD_LIBRARY_PATH=${lib.makeLibraryPath [pkgs.libheif pkgs.libjxl]}"
    ];

    # Generated by `shh service finish-profile komga.service` after a live
    # profiling run (2026-09-14) with kernel.yama.ptrace_scope temporarily
    # relaxed to 0 (see hosts/nixos/homeserver/hardening.nix). Verify after
    # rebuild that komga still serves on its port. shh's suggested
    # SocketBindDeny included "ipv4:tcp" — confirmed live 2026-09-14 this
    # breaks komga outright (Tomcat's own listening bind is a raw AF_INET
    # socket, not dual-stack IPv6 as guessed initially): "Unable to start
    # embedded Tomcat server ... Caused by: java.net.SocketException:
    # Operation not permitted". shh must have derived this from a
    # profiling window that never captured the real bind (e.g. Tomcat was
    # already listening from a prior invocation when the trace started).
    # Left out below — do not re-add "ipv4:tcp".
    ProtectSystem = "full";
    ProtectHome = true;
    PrivateTmp = "disconnected";
    PrivateDevices = true;
    PrivateMounts = true;
    ProtectKernelTunables = true;
    ProtectKernelModules = true;
    ProtectKernelLogs = true;
    ProtectControlGroups = true;
    LockPersonality = true;
    RestrictRealtime = true;
    ProtectClock = true;
    RestrictAddressFamilies = ["AF_INET" "AF_INET6"];
    SocketBindDeny = ["ipv4:udp" "ipv6:tcp" "ipv6:udp"];
    CapabilityBoundingSet = lib.mkForce "~CAP_BLOCK_SUSPEND CAP_BPF CAP_CHOWN CAP_IPC_LOCK CAP_MKNOD CAP_NET_RAW CAP_PERFMON CAP_SYS_BOOT CAP_SYS_CHROOT CAP_SYS_MODULE CAP_SYS_NICE CAP_SYS_PACCT CAP_SYS_PTRACE CAP_SYS_TIME CAP_SYSLOG CAP_WAKE_ALARM";
    # CORRECTED 2026-09-14 (second correction): the previous fix — a Nix
    # list of "~@group:EPERM" strings, one per group — was itself wrong.
    # NixOS's systemd module renders each list element as its own
    # "SystemCallFilter=" line but only the first line keeps a leading "~"
    # in the final unit; the rest silently lose it and get parsed as
    # allow-list entries, which can't carry ":EPERM" ("Allow-listed system
    # calls cannot take error number, ignoring" — confirmed live still
    # happening after the first fix, and independently this exact
    # SocketBindDeny=ipv4:tcp interaction made komga fail to bind its own
    # port outright). The documented, unambiguous pattern (systemd.exec,
    # and every real-world example found) is: set SystemCallErrorNumber=
    # once, and give SystemCallFilter a single "~"-prefixed string with no
    # per-item ":ERRNO" at all — the leading "~" then applies to the whole
    # list exactly once, no merge ambiguity.
    SystemCallErrorNumber = "EPERM";
    SystemCallFilter = "~@aio @chown @clock @cpu-emulation @debug @keyring @memlock @module @mount @obsolete @pkey @privileged @raw-io @reboot @resources @sandbox @setuid @swap";
  };

  systemd.tmpfiles.rules = [
    "d /var/lib/komga 0750 komga komga -"
    "d /var/lib/komga/tmp 0750 komga komga -"
  ];
}
