{
  config,
  pkgs,
  lib,
  ...
}: {
  users.users.komga = {
    isSystemUser = true;
    group = "komga";
    extraGroups = [
      "users"
      "media"
    ];
  };
  users.groups.komga = {};

  services.komga = {
    enable = true;
    settings = {
      "spring.datasource.url" = "jdbc:h2:file:/var/lib/komga/database;DB_CLOSE_ON_EXIT=FALSE";
      server.port = config.my.network.ports.komga;
    };
  };

  systemd.services.komga.serviceConfig = {
    UMask = "0002";
    BindPaths = [
      "/data/media/comics"
      "/data/media/manga"
      "/data/media/books"
    ];

    # komga is homeserver-only, and /tmp + /var/tmp are noexec there
    # (nix-mineral filesystem hardening default, see
    # hosts/nixos/homeserver/hardening.nix). sqlite-jdbc (bundled inside
    # komga for its search index) extracts its native .so to java.io.tmpdir
    # and mmaps it PROT_EXEC — under noexec that fails, and sqlite-jdbc
    # mis-reports the failure as "NativeLibraryNotFoundException" instead of
    # a permission error. /var/lib is already carved out exec on homeserver
    # (filesystems.normal."/var/lib" in hardening.nix, for the *arr stack's
    # own scripts) — point java.io.tmpdir at /var/lib/komga/tmp instead of
    # PrivateTmp's /tmp.
    # nixpkgs' komga wrapper only puts libwebp on LD_LIBRARY_PATH (verified
    # via `cat` on the wrapper script) — libheif and libjxl are both
    # available in nixpkgs but the package doesn't wire them in, so their
    # image-format plugins log "Could not load libheif"/"Could not load
    # libjxl" and silently disable at startup (confirmed live 2026-09-14).
    # The wrapper prepends its own LD_LIBRARY_PATH entry onto whatever it
    # inherits, so this is additive, not a fight over who wins.
    Environment = [
      "JAVA_TOOL_OPTIONS=-Djava.io.tmpdir=/var/lib/komga/tmp"
      "LD_LIBRARY_PATH=${lib.makeLibraryPath [pkgs.libheif pkgs.libjxl]}"
    ];

    # Generated by `shh service finish-profile komga.service` after live
    # profiling runs (2026-09-14) with kernel.yama.ptrace_scope temporarily
    # relaxed to 0 (see hosts/nixos/homeserver/hardening.nix).
    # nixpkgs' komga.nix hardcodes PrivateTmp, RestrictAddressFamilies, and
    # CapabilityBoundingSet (all plain, not mkDefault) — needs mkForce.
    ProtectSystem = "full";
    ProtectHome = true;
    PrivateTmp = lib.mkForce "disconnected";
    PrivateDevices = true;
    PrivateMounts = true;
    ProtectKernelTunables = true;
    ProtectKernelModules = true;
    ProtectKernelLogs = true;
    ProtectControlGroups = true;
    LockPersonality = true;
    RestrictRealtime = true;
    ProtectClock = true;
    CapabilityBoundingSet = lib.mkForce "~CAP_BLOCK_SUSPEND CAP_BPF CAP_CHOWN CAP_IPC_LOCK CAP_MKNOD CAP_NET_RAW CAP_PERFMON CAP_SYS_BOOT CAP_SYS_CHROOT CAP_SYS_MODULE CAP_SYS_NICE CAP_SYS_PACCT CAP_SYS_PTRACE CAP_SYS_TIME CAP_SYSLOG CAP_WAKE_ALARM";
    # AF_NETLINK required — without it Tomcat's own listener bind fails
    # outright ("Operation not permitted" from Net.bind0, confirmed live
    # 2026-09-14/15): Java/Tomcat's NIO endpoint needs netlink for interface
    # enumeration before bind, unrelated to AF_INET6/IPv6 despite that being
    # disabled host-wide. This was silently dropped once already by a stale
    # duplicate serviceConfig block that used to live in
    # hosts/nixos/homeserver/hardening.nix (removed 2026-09-15) — this file
    # is now the single source of truth for komga's hardening, do not
    # re-add a second systemd.services.komga.serviceConfig anywhere else.
    RestrictAddressFamilies = lib.mkForce ["AF_INET" "AF_INET6" "AF_NETLINK"];
    SocketBindDeny = ["ipv4:udp" "ipv6:udp"];
    # SystemCallErrorNumber= once + a single "~"-prefixed SystemCallFilter
    # string (not a per-item ":ERRNO" list) is the documented, unambiguous
    # pattern — a Nix list of "~@group:EPERM" strings renders as multiple
    # lines and NixOS/systemd only keeps the leading "~" on the first one.
    SystemCallErrorNumber = "EPERM";
    SystemCallFilter = "~@aio @chown @clock @cpu-emulation @debug @keyring @memlock @module @mount @obsolete @pkey @privileged @raw-io @reboot @resources @sandbox @setuid @swap";
  };

  systemd.tmpfiles.rules = [
    "d /var/lib/komga 0750 komga komga -"
    "d /var/lib/komga/tmp 0750 komga komga -"
  ];
}
