{
  config,
  lib,
  pkgs,
  ...
}: {
  imports = [
    ((import ../lib/pg-env.nix {inherit lib;}) {
      name = "bazarr";
      envLines = [
        "POSTGRES_ENABLED=true"
        "POSTGRES_HOST=127.0.0.1"
        "POSTGRES_PORT=5432"
        "POSTGRES_DATABASE=bazarr"
        "POSTGRES_USERNAME=bazarr"
        "POSTGRES_PASSWORD=%s"
      ];
      passwordSecretPath = config.sops.secrets.bazarr_db_password.path;
    })
  ];

  # Custom post-processing (Bazarr Settings > Subtitles) converts .srt to
  # .ass for languages whose glyphs some clients can't render as text
  # (e.g. Hebrew on Roku -- tofu boxes), so the server burns them in via
  # libass instead of the client rendering plain text. ffmpeg isn't
  # otherwise on bazarr's PATH.
  systemd.services.bazarr.path = [pkgs.ffmpeg];

  # Bazarr reads these same POSTGRES_* env vars natively and gives them
  # precedence over config.yaml -- no container entrypoint magic needed.
  services.bazarr = {
    enable = true;
    user = "bazarr";
    group = "bazarr";
    dataDir = "/data/media/.state/nixarr/bazarr";
    listenPort = config.my.network.ports.bazarr;
  };

  systemd.services.bazarr = {
    after = ["data.mount" "bazarr-pg-env.service"];
    requires = ["data.mount" "bazarr-pg-env.service"];
    serviceConfig = {
      EnvironmentFile = "/run/bazarr-secrets/pg-env";

      # Generated by `shh service finish-profile bazarr.service` after a
      # live profiling run (2026-09-14) with kernel.yama.ptrace_scope
      # temporarily relaxed to 0 — see hosts/nixos/homeserver/hardening.nix.
      # Unlike radarr/sonarr/prowlarr (.NET, need W+X JIT memory), bazarr is
      # Python — shh observed no W+X memory use, so MemoryDenyWriteExecute
      # is safe here. CapabilityBoundingSet is deliberately NOT taken from
      # shh's output: modules/services/nixarr/default.nix already forces it
      # fully empty for bazarr, stricter than shh's partial denylist.
      ProtectSystem = "full";
      ProtectHome = true;
      PrivateTmp = "disconnected";
      PrivateDevices = true;
      PrivateMounts = true;
      ProtectKernelTunables = true;
      ProtectKernelModules = true;
      ProtectKernelLogs = true;
      ProtectControlGroups = true;
      LockPersonality = true;
      RestrictRealtime = true;
      ProtectClock = true;
      MemoryDenyWriteExecute = true;
      RestrictAddressFamilies = ["AF_INET" "AF_INET6" "AF_NETLINK" "AF_UNIX"];
      SocketBindDeny = ["ipv4:udp" "ipv6:udp"];
      # CORRECTED 2026-09-14: shh printed this as one space-separated string
      # with a single leading "~", but systemd only applies "~" to the
      # first token of a given value — everything after it silently reverts
      # to allow-list parsing, which can't carry ":EPERM" (confirmed live:
      # "Allow-listed system calls cannot take error number, ignoring").
      # Each group needs its own "~" as a separate list entry instead
      # (systemd merges repeated SystemCallFilter= lines).
      SystemCallFilter = [
        "~@aio:EPERM"
        "~@chown:EPERM"
        "~@clock:EPERM"
        "~@cpu-emulation:EPERM"
        "~@debug:EPERM"
        "~@keyring:EPERM"
        "~@memlock:EPERM"
        "~@module:EPERM"
        "~@mount:EPERM"
        "~@obsolete:EPERM"
        "~@pkey:EPERM"
        "~@privileged:EPERM"
        "~@raw-io:EPERM"
        "~@reboot:EPERM"
        "~@sandbox:EPERM"
        "~@setuid:EPERM"
        "~@swap:EPERM"
      ];
    };
  };
}
