{
  config,
  lib,
  ...
}: {
  imports = [
    # prowlarr_db_password is mode 0440 owner=postgres group=prowlarr.
    ((import ../lib/pg-env.nix {inherit lib;}) {
      name = "prowlarr";
      envLines = [
        "PROWLARR__POSTGRES__HOST=127.0.0.1"
        "PROWLARR__POSTGRES__PORT=5432"
        "PROWLARR__POSTGRES__USER=prowlarr"
        "PROWLARR__POSTGRES__MAINDB=prowlarr"
        "PROWLARR__POSTGRES__LOGDB=prowlarr-log"
        "PROWLARR__POSTGRES__PASSWORD=%s"
      ];
      passwordSecretPath = config.sops.secrets.prowlarr_db_password.path;
    })
  ];

  # Prowlarr reads PROWLARR__POSTGRES__* env vars natively (same mechanism as
  # every other Servarr app) -- no need to hand-edit config.xml via xmlstarlet.
  services.prowlarr = {
    enable = true;
    dataDir = "/data/media/.state/nixarr/prowlarr";
    settings.server.port = config.my.network.ports.prowlarr;
  };

  systemd.services.prowlarr = {
    after = ["data.mount" "prowlarr-pg-env.service"];
    requires = ["data.mount" "prowlarr-pg-env.service"];
    serviceConfig = {
      EnvironmentFile = "/run/prowlarr-secrets/pg-env";

      # nixpkgs' prowlarr module already sets DynamicUser=yes and
      # ProtectSystem=strict, but leaves CapabilityBoundingSet at the full
      # default set (verified via `systemctl show prowlarr.service`) — same
      # gap as bazarr/lidarr, unrelated to those two axes. Unlike bazarr,
      # prowlarr is a pure indexer proxy with no media-library filesystem
      # access outside its own dataDir (already granted, since it already
      # runs fine under ProtectSystem=strict), so the fuller set is safe
      # here.
      CapabilityBoundingSet = lib.mkForce "";
      NoNewPrivileges = lib.mkDefault true;
      PrivateDevices = lib.mkDefault true;
      # No AF_INET6 — homeserver-only module, networking.enableIPv6 = false
      # there. nixpkgs' upstream default here is AF_INET/AF_INET6/AF_UNIX;
      # with AF_INET6 present, `shh` (strace-profiling hardening helper)
      # crashes reading /proc/sys/net/ipv6/bindv6only, which doesn't exist
      # when IPv6 is fully disabled (confirmed live 2026-09-14, same crash
      # radarr/sonarr's comments already flagged this file as hitting).
      RestrictAddressFamilies = lib.mkForce ["AF_INET" "AF_UNIX"];
      ProtectClock = lib.mkDefault true;
      ProtectKernelLogs = lib.mkDefault true;
      ProtectKernelModules = lib.mkDefault true;
      ProtectKernelTunables = lib.mkDefault true;
      ProtectControlGroups = lib.mkDefault true;
      ProtectHostname = lib.mkDefault true;
      ProtectHome = lib.mkDefault true;
      RestrictNamespaces = lib.mkDefault true;
      RestrictSUIDSGID = lib.mkDefault true;
      LockPersonality = lib.mkDefault true;
      RestrictRealtime = lib.mkDefault true;
      ProtectProc = lib.mkDefault "invisible";
      ProcSubset = lib.mkDefault "pid";
      UMask = lib.mkDefault "0077";
      RemoveIPC = lib.mkDefault true;
      # Deliberately NOT setting MemoryDenyWriteExecute: *arr apps run on
      # .NET, whose JIT needs W+X memory — same risk class that killed
      # alloy.service (Go) on gcp-relay. Not worth testing against the
      # whole *arr stack's indexer proxy.
      #
      # PrivateMounts/SocketBindDeny/SystemCallFilter below generated by
      # `shh service finish-profile prowlarr.service` after a live
      # profiling run (2026-09-14) with kernel.yama.ptrace_scope
      # temporarily relaxed to 0 and ProtectProc/ProcSubset temporarily
      # loosened (see hosts/nixos/homeserver/hardening.nix) — see git
      # history for that temporary diff, since reverted. shh also
      # suggested ProtectSystem=full and a partial CapabilityBoundingSet
      # denylist; both are weaker than what's already set above (strict
      # from nixpkgs, and fully empty here), so not applied.
      PrivateMounts = true;
      SocketBindDeny = ["ipv4:udp" "ipv6:tcp" "ipv6:udp"];
      # Single-line value, exactly as shh printed it: the leading "~"
      # inverts the whole list into a denylist — splitting this into
      # separate Nix list entries would emit multiple systemd directive
      # lines and only the first would carry the "~", breaking the
      # semantics.
      SystemCallFilter = "~@aio:EPERM @chown:EPERM @clock:EPERM @cpu-emulation:EPERM @debug:EPERM @keyring:EPERM @memlock:EPERM @module:EPERM @mount:EPERM @obsolete:EPERM @pkey:EPERM @privileged:EPERM @raw-io:EPERM @reboot:EPERM @sandbox:EPERM @setuid:EPERM @swap:EPERM";
    };
  };
}
