name: push
on:
  workflow_dispatch:
  push:
  pull_request_review:

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Access private repository
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.GH_PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v19
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13
      - run: git config --global --add safe.directory "${PWD}"
      - run: nix flake check --accept-flake-config
