name: Update Flake
on:
  schedule:
    - cron: '0 0 * * 0'  # Еженедельно
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Обновить версию
      - uses: cachix/install-nix-action@v25  # Обновить версию
      - uses: cachix/cachix-action@v14
        with:
          name: homeserver
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      
      - name: Update flake
        run: nix flake update
      
      - name: Test build
        run: nix build .#nixosConfigurations.homeserver.config.system.build.toplevel
      
      - name: Create PR
        uses: peter-evans/create-pull-request@v5  # Обновить версию
        with:
          title: "chore: update flake inputs"
          commit-message: "chore: update flake inputs"
          branch: update-flake
          delete-branch: true