cloudflare_prometheus_exporter_token: ENC[AES256_GCM,data:iIrUXPXA2WBOzH/PJ7LgXmpbFY5Zu5/uqmolp2L5LlNFalgPdQBmqA==,iv:LeR6galGaX0l5K6voe3aBdEL1nqac9F/iNzueH690jc=,tag:h6cSF4bgJnZACFpGdkCShw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVT3VLS2RPSFpDQnZETTc1
            REU5am9yU3UzeldqOWg0aU4xNlFpZjRBU1hrCi9SbktRMU5OMjZsYkxETHd4WWlI
            WU5ob0hRZVgwMkI4WXA5MnJiczBtZTAKLS0tIEh6VXQ2WTl5MzR5SjFFSFVORFVD
            MVo5SGJwMldVRmdxRlBDYjU0WVo3UlUK1bI+esVPoQEFu+jr1k33ZtTvQLB1Loht
            V9knldw93xl8Z6D9DhZNrcdLfWnjft3MqmEjUBQXJJvhYZ2rBvbR0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18pkk5washz5p8vl4tkemulvv8x23deaqwqqvfmwu7r7vwvjfwdqsg657vd
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscnByRXloN051Ynp1b2dX
            ODdGaDQreVhYZkRCbWxtazV5amFPVGFMdm1JCkVKNlNRV0VaTHh5S2FTVStuUHdH
            c016eUI0cFFGREt4dUpiUy84dVFQcjQKLS0tIExHTGdCdUVwTVMySjMvK2Q1c043
            NXFibjBzbDlOakphVkwzcWFDNmQyT0EKcD3WGJpN2pesDlU7u6iCejBqI0UzO0rt
            QyhS1v0tVGnYX4YKVEnmupagUdoqztgfkyvYlaaEGa9tJaSvdkLYPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age156neere9qg5ry92ru8tckjcf9h2zn3xdrs6ywzq7cuhg7v8m3s0qka8p8k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1S1RTR1ZNNDkrZEg2b3JY
            bjNMNHJrYlRINHBZNXU3d2pyOENFa1dSY0UwCkJUNGVzSU96NmZ2N3RDNzY1b2Ew
            ZDlkTm5KVE0vVWFydzJ0TjUzSGV4SzAKLS0tIHNIQmZZeERKVko4MnJVV2VMMnAv
            L3U4MUludG9hNVcvTHJMTmt0UWhyNzAKhVi+BoRWa2FSWFQfmUDpFlonBriOXuuu
            SwLepfSorYmf4xDrx1pqme3UaS73TOqpW74Ric93B0wPCLby5yjPqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnavzptapglqmf4pmvecdhdrysykwhxk0u5mef5rvhjtqdrxcckszqsav6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSajNVQWNmb2xkbk8yelQ5
            VjlTVytZMG1obHV3VUNtQzFDS1ZKTC9YVlJZClZtaXN3aFQ3MEhzMXFPdkVkcEJy
            UXZDUEYxeDN1U3pkWXNHd3YrMGJiOUEKLS0tIDVSbk5NS2UvTmg5YWlOTGZBMzZV
            WTkvck1MNWV4Y250b2pSeSt2YkFDYncK7sN3bOQUsb2eP4/d3jhcoTHguJNz1uzl
            ZtWGkzuDv6UxQiTeo4/KTF8AetdN0uW8lbRyc79AggAYoCh5/fAzHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fsjqjx77t6yhfvdgq8a69aggh36jv0fjm53u26tlqvs73lkpgutsssdttd
    lastmodified: "2025-08-05T20:55:34Z"
    mac: ENC[AES256_GCM,data:RnvFP2dk1jvdjpSqNRhAZenLdPYer1RCV69876XYYJdunj6jJIcu+fjWv2bsfhM4tXkoVNJhZr/O+BLolxhwUvRs9bhNF+AR0IpHxYQrlhGPUOVUU/vvDWk4tS9lrPYfQG0kMiJ7pz8DCbt6SAQcGA8ITFDDZO7rsMqml5gNCjI=,iv:xXCY1D/N5qTDMqWKn2tOotXNia9dAzAfpcmwECqXC8I=,tag:s+5oXnwVItTsA2JsUY+B7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
