cloudflare_prometheus_exporter_token: ENC[AES256_GCM,data:iIrUXPXA2WBOzH/PJ7LgXmpbFY5Zu5/uqmolp2L5LlNFalgPdQBmqA==,iv:LeR6galGaX0l5K6voe3aBdEL1nqac9F/iNzueH690jc=,tag:h6cSF4bgJnZACFpGdkCShw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMHk3Q25IYkRwNWFYeVFH
            bTRGMXB0V1JJNHpQVEdNQlFhK1RIaWxQYTNNCm4vN0pzK20wWjkvMGVWVkQyNlFx
            b2d1MjNiMXo0aTBkbk0vWmxYOGZLNE0KLS0tIE1GekpFYzI3a0pIdmViaVltTXZn
            VEZkYnRTUXA3cEtvWlZjQ3lSbXFGQzQKtYPGuRUmdmFMAUYl/IifK4khm3q9fX88
            zHwiCLar1b4vTWkADxE2aX/+AiPElISCQ3dIyQUIHNBdXrzhF5I7iA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18pkk5washz5p8vl4tkemulvv8x23deaqwqqvfmwu7r7vwvjfwdqsg657vd
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbnE0UUxEendRdnFGakJs
            VEZDa2xPM3lSTlpNYVVqdktiazNESzR4a0FVCmxQVEdhTGhMdW5GU0FveGQ4YnZz
            ZElXaW05dG1pVlYxQVNuaUR5LzdhTjAKLS0tIENNYXNQYzdyL0VDdzkzWkV3Y0o2
            S0JHZThYdEhLTHFYY2FKN1d5UEFWN1UKmeyez91Djn/j3imwFVpWGKzQC9LVqhHJ
            S7bU+9J5w/+PvJeBZHc6rZKzWFIvcHShggLgQrMRA7ZonLaBb2+6cQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age156neere9qg5ry92ru8tckjcf9h2zn3xdrs6ywzq7cuhg7v8m3s0qka8p8k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOTJQSTJ0TTV4MWlhdkdR
            RHB3UDRieXVXcXlGRjJ3VFpxWlBjUzlENkNZCno3YkNpZ09VbXNaRjVDaVlFUmNE
            ejhqSHpqY3Z2a3FveENEeElqWEF6NHcKLS0tIFAwT2ozTzMvR1NVTkc0WTQycmtE
            SnFQM0hJeE1WNGZ0clRSVEYrYXI1ZkUKxt97b7z8YcTNDADLGadOaQkZbhzqn/JV
            c0xG1bTgwrT8mtzQHfR2H1pN+x/KXknJvz2X+eWY5O9q1WlhvixYLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnavzptapglqmf4pmvecdhdrysykwhxk0u5mef5rvhjtqdrxcckszqsav6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQTlrcGNRRjJxNDVTOWww
            SHBIaW5pZnpqdXN3Q0RHckIzVU1lTVZJN1ZJClZXOXVrQ25RTGMxVXNSazdZT0lB
            UzY3aW1zREI5RUhYdlVvOG53TWp1d00KLS0tIHRuTDU2bDF1ajNCeUM5YzVIRGNR
            ZjFOemJaQTAxQ0tETU1ia0d2cnVsRlUKTFrKnC7Xf8ff2hnSw00hDnBhjmTFby4R
            L1SRiNdce9/GiS+xbu9odMblBXWhrwZNrQtTpKva6LLc+1zLibUtGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fsjqjx77t6yhfvdgq8a69aggh36jv0fjm53u26tlqvs73lkpgutsssdttd
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbzgxbHZNT0o4UWpkQTd4
            U3BQTnBzclUxbnRpYXVWTUc3RnI5ZlhQdVdFCldKTVYxK1hhR01jVUNGeG94OW9N
            YmludzNJYy9lSzVvU2gzd2k2YkdTSFUKLS0tIFJZSHNVaDJOd2hqdW5JL2xMRllC
            eXg5RzdPTVNzUHFNSjNxTTNsWkVnWncKsn+EhRQu6L8riLNjR7bx55r909kbKzot
            /WmurM04pJdlYzLUyuV/R4LlBZ/KWSAtBX7qOQhAcAvEYyotCHR6Xg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y27m7cd4prs827vevceq8fun9wm9r3el2srsmukgcyag23f8dfrsjchvgr
    lastmodified: "2025-08-05T20:55:34Z"
    mac: ENC[AES256_GCM,data:RnvFP2dk1jvdjpSqNRhAZenLdPYer1RCV69876XYYJdunj6jJIcu+fjWv2bsfhM4tXkoVNJhZr/O+BLolxhwUvRs9bhNF+AR0IpHxYQrlhGPUOVUU/vvDWk4tS9lrPYfQG0kMiJ7pz8DCbt6SAQcGA8ITFDDZO7rsMqml5gNCjI=,iv:xXCY1D/N5qTDMqWKn2tOotXNia9dAzAfpcmwECqXC8I=,tag:s+5oXnwVItTsA2JsUY+B7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
