cloudflare_prometheus_exporter_token: ENC[AES256_GCM,data:iIrUXPXA2WBOzH/PJ7LgXmpbFY5Zu5/uqmolp2L5LlNFalgPdQBmqA==,iv:LeR6galGaX0l5K6voe3aBdEL1nqac9F/iNzueH690jc=,tag:h6cSF4bgJnZACFpGdkCShw==,type:str]
sops:
    age:
        - recipient: age18pkk5washz5p8vl4tkemulvv8x23deaqwqqvfmwu7r7vwvjfwdqsg657vd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUkZlWjgzSkhEQzVnRVJQ
            bEc2Tm8vdy9ETjdRaWh1VWRHSmJHZTI1emhRCk5LamxIbmd3c0o3VXE1TVFDblVj
            NHdkTzFWMHdReGF6cElUSk5lVDNsQzAKLS0tIFpvSmNXRVFtUXhwOGdGYXgwWlZw
            YTJzd0RTRWw4UjRJRDI4ZDdVc1d1bzgKS/daPNdTI0YOn5fukuMsPvuKQVNB9yus
            HzFyVK0wbiXxHQehT7SMQ+hxnT5vJdm7FlV+06qkDzBpndtSyqkIsA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h9kk9fktkn0t2yk7m89jxlf2atl0808ewn3j5updmq8knt0c84uqs24ew4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSHR4d0JYYWRhcExGRWN3
            aFdBTkF4UURaUk5SQTBJd0FyRnRlQmFMaFQ4CmcrWVZqeEUzanJDL2d6S2JCWGFk
            ay9pbjMycHhJZUJ3V3dQZGtjNWRQNFEKLS0tIG1WYSs1TnBHQXB3TE5LVDIyMnhX
            WWVPMWZuYzBmaVdLTmxnYmgxUTZoTlUKpn0K+ZrKZZZfQPmId9mj3BMdRFlFh0KC
            wnJszdPXRU88KgiPAwBTNIJ57PPR5vvUJ4oUSPi9Du4EzGEHx4QgfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T20:55:34Z"
    mac: ENC[AES256_GCM,data:RnvFP2dk1jvdjpSqNRhAZenLdPYer1RCV69876XYYJdunj6jJIcu+fjWv2bsfhM4tXkoVNJhZr/O+BLolxhwUvRs9bhNF+AR0IpHxYQrlhGPUOVUU/vvDWk4tS9lrPYfQG0kMiJ7pz8DCbt6SAQcGA8ITFDDZO7rsMqml5gNCjI=,iv:xXCY1D/N5qTDMqWKn2tOotXNia9dAzAfpcmwECqXC8I=,tag:s+5oXnwVItTsA2JsUY+B7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
