[Interface]
PrivateKey = wF61kI5glJtdRIRfVnxamW0VUDZjo20qj98Y3TLyQlw=
Address = 10.139.219.153/32,fd7d:76ee:e68f:a993:b19e:3737:ad74:9a30/128
DNS = 10.128.0.1, fd7d:76ee:e68f:a993::1
MTU = 1320

[Peer]
PublicKey = PyLCXAQT8KkM4T+dUsOQfn+Ub3pGxfGlxkIApuig+hk=
PresharedKey = dAno9aSu5IuQjIkii5TEOqJCrTdwesUpbkkwnnF5Fis=
Endpoint = 192.30.89.77:1637
AllowedIPs = 0.0.0.0/0,::/0
PersistentKeepalive = 15

[Peer]
PublicKey = PyLCXAQT8KkM4T+dUsOQfn+Ub3pGxfGlxkIApuig+hk=
PresharedKey = dAno9aSu5IuQjIkii5TEOqJCrTdwesUpbkkwnnF5Fis=
Endpoint = 198.44.157.13:1637
AllowedIPs = 0.0.0.0/0,::/0
PersistentKeepalive = 15

[Peer]
PublicKey = PyLCXAQT8KkM4T+dUsOQfn+Ub3pGxfGlxkIApuig+hk=
PresharedKey = dAno9aSu5IuQjIkii5TEOqJCrTdwesUpbkkwnnF5Fis=
Endpoint = 184.75.221.37:1637
AllowedIPs = 0.0.0.0/0,::/0
PersistentKeepalive = 15

[Peer]
PublicKey = PyLCXAQT8KkM4T+dUsOQfn+Ub3pGxfGlxkIApuig+hk=
PresharedKey = dAno9aSu5IuQjIkii5TEOqJCrTdwesUpbkkwnnF5Fis=
Endpoint = 199.189.27.125:1637
AllowedIPs = 0.0.0.0/0,::/0
PersistentKeepalive = 15